### PR TITLE
should be working now

### PR DESCRIPTION
**Pull request by g-sam**

### CODE REVIEW

**Comment by daymos** [comment]
am reviewing

**Comment by g-sam** [comment]
btw if you are wondering about the pt.matrixTransform operations, in every case I am using this it is because I have obtained co-ordinates in screen space and need to convert them to co-ordinates in the svg. getScreenCTM() provides the transformation matrix for this.

**Comment by daymos** [comment]
Pretty cool. the color rescaling seems to still be barely visible when using the box. only if you zoom in a lot. Also if i click while in the box i get a blank screen

**Comment by daymos** [comment]
i still have to read the code carefully

**Comment by g-sam** [comment]
I can make the code easier to follow i think, so you might prefer to wait. might not get round to doing tht for a few days though.
the clicking thing is one of the issues.
also, the whole way of having to toggle select mode is rather clunky. need something easier.

**Comment by g-sam** [comment]
also, I was thinking about the way calibration is done. I think one problem currently is that if you have all positive scores in the selected area you will still get the full range of colours. it might make more sense to tie the middle colour to zero change so you know which countries have gone up and which down.

**Comment by g-sam** [comment]
and another thing: the zoom should take you to the min bounding box of all the selected countries rather than the selectbox, otherwise select usa and alaska will be off screen.

**Comment by daymos** [comment]
agree with what you suggests. If you need some help let me know

**Pull request merged**
